baseURL: https://govflow.org/
languageCode: en-us
title: Gov Flow
theme: fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: An open, modular work order and workflow management system for local government and residents.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: 311 for smart cities.
    # Hero subtitle (optional)
    subtitle: An open, modular work order and workflow management system for local government and residents.
    # Button text
    buttontext: Get the code
    # Where the main hero button links to
    buttonlink: "https://github.com/govflow/govflow"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Solutions
    sublinks:
    - title: Open 311 v2 GeoReport Software
      url: /open-311-software/
    - title: Service Request Management for Cities
      url: /service-request-management-for-cities/
    - title: SaaS Solution for 311
      url: /saas-solution-for-311/
  - title: Managed Gov Flow
    url: /managed-services/
  - title: Contact
    url: /contact/
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    # logo: fresh-square
    # sections:
    # - title: User
    #   icon: user
    #   links:
    #   - text: Profile
    #     url: /
    #   - text: Account
    #     url: /
    #   - text: Settings
    #     url: /
    # - title: Messages
    #   icon: envelope
    #   links:
    #   - text: Inbox
    #     url: /
    #   - text: Compose
    #     url: /
    # - title: Images
    #   icon: image
    #   links:
    #   - text: Library
    #     url: /
    #   - text: Upload
    #     url: /
    # - title: Settings
    #   icon: cog
    #   links:
    #   - text: User settings
    #     url: /
    #   - text: App settings
    #     url: /
  section1:
    title: Dynamic, future facing cities.
    subtitle: A fully featured, open source, platform for 311 and service request management.
    tiles:
    - title: Improve resident service
      icon: mouse-globe
      text: See all resident requests in one place and make decisions on how to improve servicex`
      url: /contact/
      buttonText: Easy to use
    - title: Flexible
      icon: laptop-cloud
      text: Add workflows and request types without needing to code.
      url: /contact/
      buttonText: Get started
    - title: Data driven
      icon: plug-cloud
      text: Comes with an analytics layer out of the box.
      url: /contact/
      buttonText: Get started
  # section2:
  #   title: Easy to use
  #   subtitle: Empower staff with minimal IT involvement
  #   features:
  #   - title: Powerful and unified interface
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-globe
  #   - title: Cross-device synchronisation
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: doc-sync
  #   - title: Nomad system
  #     text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #     icon: mobile-feed
  # section3:
  #   title: Flexible
  #   subtitle: Add workflows and request types without needing to code.
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Data driven
  #   subtitle: Comes with an analytics layer out of the box.
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/govflow/govflow
      icon: github
    - link: https://zencity.io
      icon: website
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Key features
          link: /features/
        - text: Discussion forum
          link: https://github.com/govflow/govflow/discussions
        - text: Issue tracker
          link: https://github.com/govflow/govflow/issues
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: https://github.com/govflow/govflow/#README
        - text: User guides
          link: https://github.com/govflow/govflow/#README
        - text: Admin guide
          link: https://github.com/govflow/govflow/#README
        - text: Developers
          link: https://github.com/govflow/govflow/#README
      column3:
        title: "Community"
        links:
        - text: ZenCity
          link: https://zencity.io
